version: '3.9'

services:
  database:
    image: mongo:5.0
    volumes:
      - ./mongo-db:/data/db
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE= livechat
      - MONGO_INITDB_ROOT_USERNAME=theroot
      - MONGO_INITDB_ROOT_PASSWORD=thepass